name: Build ArikTube Materialious container

on:
  workflow_dispatch:
  push:
    branches:
      - arik

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./materialious

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install modules
        run: npm ci

      - name: Run svelte checks
        run: npm run check

      - name: Check linting
        run: npm run eslint

      - name: Attempt to build codebase
        run: npm run build && npm prune --omit=dev

  build:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/neskiredk/materialious
          flavor: |
            latest=false
          tags: |
            type=raw,value=latest
            type=sha

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./materialious
          file: ./materialious/Dockerfile
          platforms: linux/amd64
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
